### ISSUE TITLE
LV2 Custom data seems to be required when plugins is load files

### ISSUE THREAD

**Issue by jean-emmanuel** [Stazed/non-mixer-xt#17]
LSP Impulse Response doesn't save loaded impulse file in its state while LSP Impulse Reverb does and the reason seems to be that the former doesn't have enough parameters to trigger the use of a custom data folder. I see there's a hardcoded list of plugins in LV2_Plugins.C which I guess is there precisely for this kind of issue but isn't there a way to reliably decide whether custom data is needed without maintaining such a list ? Another solution, arguably overkill but also quite convenient (since ttl state files are human-readable)  would be to always use custom data for lv2 plugins. What do you think ?

**Comment by Stazed** [comment]
Yes, the list of custom data required plugins is an ugly hack. It comes down to:
>...but isn't there a way to reliably decide whether custom data is needed without maintaining such a list ?

I would think that there would be a way, but I am no expert on LV2 and this host implementation is a jigsaw puzzle of different parts that I crammed together to get working.  There seems to be literally no documentation for host implementation, and if you know of any LV2 expert that might shed some light on how to handle plugins that do not expose parameters to the host,  do to custom gui requirements, please have them educate me.

Using custom data for all LV2s I suspect is the only reliable way to handle this, but we would still need to support the direct parameter loading for backwards compatibility. In addition, I believe that plugin loading is faster in most cases with direct parameter loading. The is also a problem that some of the larger plugins need a delay after initial loading, before loading the state ttl files. Again, I do not know of any way to identify these plugins other than a list and direct testing. I used the custom data requirement to set the delay, but if all plugins use custom delay, then another method or list must be maintained as projects with a large number of LV2 plugins would take an exceedingly long time to load.

I also found that some of my larger projects (with over 30 LV2s) would result in huge intimidating project folders with many more files that seemed very large and bloated. Realistically, very few plugins actually need custom data, but unless there is some way to identify them, big bloated project folders may be the only option.

Another option might be to lower the custom data requirement to 20 parameters, but that still would not catch all plugins requiring custom data, since some plugins with literally hundreds of parameters show few or none in the .ttl files.

Maybe someone with better LV2 expertise could be persuaded to enlighten me about how to handle plugins that require special data handling for file saving and loading...

**Comment by jean-emmanuel** [comment]
> Maybe someone with better LV2 expertise could be persuaded to enlighten me about how to handle plugins that require special data handling for file saving and loading...

Maybe @falkTX could give some pointers ? Possibly something to be discussed on IRC though.

**Comment by Stazed** [comment]
Found a way to set the custom data flag that should work in all cases and is not quite the overkill that 'always' would be. Simply use custom data when any atom ports are exposed by the plugin. It simplifies things and won't bloat up the project directory as much. Still seems like a kludge to me, as not all plugins with atom ports need special handling... I will wait a while to see if anyone comes up with a more direct method before implementing it.

**Comment by Stazed** [comment]
Went ahead and pushed this to the wip branch. Reopen if you find any other file saving/loading problems related to this.

**Comment by jean-emmanuel** [comment]
thanks !

Le 19/03/2023 à 14:52, Stazed a écrit :
