### ISSUE TITLE
cmake doesn't check properly ntk in Debian Bookworm

### ISSUE THREAD

**Issue by orlammd** [Stazed/non-mixer-xt#25]
After git cloning ntk, and sucessfully installing it, cmake stops complaining that ntk is not installed.
Commenting the two lines concerning ntk in the cmake conf files fix the problem, but then, it's not possible to build non-mixer-xt.
ntk lays in /usr/include/ntk after an install using ./waf configure --prefix=/usr.
Thank you.

**Comment by Stazed** [comment]
Not sure why cmake cannot find ntk, but you can edit the CMakeCache.txt file in the non-mixer-xt build directory to set the location of the ntk libraries. Below is what is in my ubuntu CMakeCache.txt for ntk:
>//Path to a library.
pkgcfg_lib_NTK_IMAGES_cairo:FILEPATH=/usr/lib/x86_64-linux-gnu/libcairo.so

>//Path to a library.
pkgcfg_lib_NTK_IMAGES_ntk:FILEPATH=/usr/local/lib/libntk.so

>//Path to a library.
pkgcfg_lib_NTK_IMAGES_ntk_images:FILEPATH=/usr/local/lib/libntk_images.so

>//Path to a library.
pkgcfg_lib_NTK_cairo:FILEPATH=/usr/lib/x86_64-linux-gnu/libcairo.so

>//Path to a library.
pkgcfg_lib_NTK_ntk:FILEPATH=/usr/local/lib/libntk.so

Also, I would suggest that you install ntk in */usr/local/* instead of */usr/* which is the default location for the package if not installed from the debian repository. Do  **./waf uninstall** first, then **./waf configure** without the *--prefix=/usr*.

**Comment by orlammd** [comment]
To go a bit further:
orl@PortableORL:/usr/local/lib$ pkg-config --libs ntk
-L/usr/local/lib -lntk -lcairo 
orl@PortableORL:/usr/local/lib$ pkg-config --modversion ntk
1.3.1001

Please note it's the same on 3 different machines, with a Debian bookworm uptodate, so it's probably not a local problem.

**Comment by Stazed** [comment]
I just noticed that Debian bookworm was just released February 10. I have run into this problem with other distributions and running the very latest releases. Seems some environment variables ( PKG_CONFIG_PATH) can be missed with the initial releases. That is why I wait a few months before trying the latest...

If it passes cmake with link but does not build, then you might try ntk with **./waf configure --prefix=/usr/local/**. Linking probably works for cmake because it finds the .so, but fails on build because the .so is still pointing to /usr/local/lib64/. You just need to find the correct location to install ntk and append the  PKG_CONFIG_PATH to the location. Also check what the CMakeCache.txt file is showing to be sure of the location.

**Comment by orlammd** [comment]
OK, I'm going to try this.
There's something I don't get, still: the failure occurs on Fl_SliderX.C, but FL/fl_draw.H is already called and used in Fl_ValueSlider.C which doesn't fail. Even if Fl_ValueSlider.C doesn't use that fl_color_add_alpha method, it suggest that the library is correctly linked at that point, isn't it?

Could it be problematic that I have fltk installed also?

**Comment by orlammd** [comment]
OK, my fault: in my many manipulation, I forgot to uncomment the two lines concerning ntk in the CMakeLists.txt.
So to get it working, you just have to set PKG_CONFIG_PATH=/usr/local/lib64/pkg-config before cmake.
