### ISSUE TITLE
Thanks for your work 

### ISSUE THREAD

**Issue by jean-emmanuel** [Stazed/non-mixer-xt#3]
Hi ! Your fork looks like a true game changer :)

I'm just shimming in to list the very few things that would make it a dream come true (I had all of these implemented in a [fork](https://github.com/PlagiatBros/non/commits/master) that we use extensively on stage but I suspect you might come up with a better implementation if you were to find these relevant):
- fix sending `*/unscaled` osc feedback
- allow querying strip meter levels (or subscribing to level changes at a limited rate)
- allow querying plugin output control signals (such as a compressor's gain reduction)

(These changes allow us to generate a (web based) remote controller for non-mixer)

**Comment by Stazed** [comment]
Hello @jean-emmanuel 

I currently do not have an OSC controller and am not that familiar with its usage.
I use the midi-mapper for all my automation :).

If you want to add any of your stuff to this project I would accept a PR.
I did pull in the NSM optional gui feature from your fork (Thank you!!!), but I simply do not have
enough experience with OSC to know even how these changes would be used.

If you do want to send a PR, make the changes from the "wip" branch and perhaps encase them in:
>#ifdef SOME_FEATURE

So that they could be enabled/disabled via cmake if they should be considered "experimental" or just
specific to your needs.

**Comment by jean-emmanuel** [comment]
Great, I'll try to come up with a PR then, thanks again :)
