### ISSUE TITLE
Klangfalter's LV2 file browser doesn't open, with its VST2 version it works

### ISSUE THREAD

**Issue by suedwestlicht** [Stazed/non-mixer-xt#36]
Klangfalter is a convolution reverb contained in DISTRHO-ports https://github.com/DISTRHO/DISTRHO-Ports

The LV2 version cannot open its file browser window.

![Bildschirmfoto_2024-05-04_19-32-34](https://github.com/Stazed/non-mixer-xt/assets/5550538/fe156f66-e918-45b8-8fd8-96d025c42000)

**Comment by Stazed** [comment]
The LV2 version does not work in Carla or Jalv either. It works in Qtractor and Muse. Seems like the issue is with X11 resizing. In checking the debug logs, the mixer gets and sends the resize message to the plugin, but the plugin does not respond. This looks like a plugin side issue, and the reason it works with Qtractor and Muse is they most likely use Qt embedded X11.  I do not see anything from the mixer side that is going wrong here. 

Is there a reason you cannot use the VST2 version?

I have found that most plugins that offer multiple formats, usually work best in one format and the others have various issues. So I just use the one that works best.

If you really want to use the LV2 version, DISTRHO also has a mini  LV2 Carla plugin host that works well in the mixer and the browser works for Klangfalter.
 
> https://github.com/DISTRHO/Ildaeil

If your distro is Arch or derivatives, it is published in the AUR.

**Comment by suedwestlicht** [comment]
Thanks for investigating and explaining. I prefer LV2 plugins but I can live with Klangfalter's VST2 version in Non Mixer XT. Additionally, there's plenty of convolution reverbs I can use.

**Comment by Stazed** [comment]
@suedwestlicht , I just pushed a change to the wip branch that looks like it fixed the browser issue for LV2.

**Comment by suedwestlicht** [comment]
Confirmed. Thank you.

**Comment by suedwestlicht** [comment]
But the display bug in the numeric input field of Gain has returned.
